run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gofmt
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
