version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: merch_service
      PGDATA: /var/lib/postgresql/data/
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: